### ISSUE TITLE
Typos in  two Wiki pages found

### ISSUE THREAD

**Issue by dwydler** [neos-sdi/adfsmfa#382]
**Describe the bug**
Ich habe 2 bzw. 3 Fehler in der Dokumentation bzw. Wiki gefunden. Leider habe ich es nicht geschafft, dafür Pull Request zu erstellen. Daher dieses Issue mit dem Verweis die gefundenen Fehlern.

I found three typos in the documentation/wiki. Unfortunately, I haven't been able to create a pull request for them. Therefore, I'm creating this issue with a link to the errors I found.

https://github.com/dwydler/adfsmfa/commit/d4e6518199bc7938560daa58e8610787fbe58d67
https://github.com/dwydler/adfsmfa/commit/13383bdd223ca017d7cbb91ad14d4f9cbeedb6e8

**Comment by redhook62** [comment]
Done !

**Comment by dwydler** [comment]
I still see the typos on both pages in the wiki.
Could a cache be affecting this?

**Comment by redhook62** [comment]
https://github.com/redhook62/adfsmfa/wiki/01-Installation#backup-and-restore-mfa-configuration
https://github.com/redhook62/adfsmfa/wiki/06-Data-Storage#sample-1

**Comment by dwydler** [comment]
As you can see, the colon after the char c is missing.
<img width="1250" height="484" alt="Image" src="https://github.com/user-attachments/assets/ed32431f-eb16-4575-bfe9-80a442b31492" />

**Comment by redhook62** [comment]
Yes, if you want !
