### ISSUE TITLE
Customized English text is not used on non-supported languages

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#71]
Hi,
We use the  "Localizing MFA Web parts" to customize some text, and it works fine.

However, when a browser is configured for a language that does not exist in the MFA adapter (for example Swedish) it defaults back to English, which is good, but it is then showing the non-customized English text. When the browser is set to English the customized English text shows up nicely.

Regards,
Andreas

**Comment by redhook62** [comment]
Hi Andreas

Please wait some few days for a new Release.
We are Working on Synchonization of servers when you are using WID configuration, And not replay of TOTP code.
Note that, this future version project is using Visual Studio 2017 and is targeting framework 4.7.2.

Regards

**Comment by redhook62** [comment]
Done in version 2.4.0.1001

Regards

**Comment by anorstrom** [comment]
Hi,
I tried latest version 2.4.4720.0000, but this didn't work (didn't test 2.4.0.100.). 
I still get the non-customized English text when the browser language is a non-supported and it defaults back to English.

Thanks,
Andreas

**Comment by redhook62** [comment]
Hi,

Yes, it's a mistake.
Some changes were forgotten when we changed our build environment.
We will provide a corrected version this Week End, 
We will also provide the msi 2.4.0.1000.

Best Regards

**Comment by redhook62** [comment]
Done in version 2.4.4720.0001

Regards

**Comment by anorstrom** [comment]
Thanks! Tested and it is now working :)
